version:     "0004--21-Mar-2022"
copyright:   "2022"
author:      "Francois Ferdinand Dahny Ginting"
title:       "OS221: Operating Systems 2022-1"
githublink:  "https://github.com/fferdinandg/os221/"
myloglink:   "TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
